name: "Alarmserver ip cam"
description: "My first real add-on!"
version: "1.0.0"
slug: "alarmserver"
init: false







description: >-
  "Long description"
arch:
  - amd64
url: "website with more information about add-on (e.g., a forum thread for support)"
ports:
  123/tcp: 15002
map:
  - config:rw
  - ssl
image: repo/{arch}-my-custom-addon
